### PR TITLE
enforce version for exec-maven-plugin

### PR DESCRIPTION
**Pull request by azbarcea**
use version 1.6.0 for exec-maven-plugin

### CODE REVIEW

**Comment by CMoH** [comment]
Maybe this will help: https://github.com/apifocal/apifocal-parent/blob/master/pom.xml#L144 - this in `apifocal-parent:8-SNAPSHOT`. I'm planning to release this when silkmq-0.13.0, but there's no reason to release `apifocal-parent` earlier.

**Comment by hzbarcea** [comment]
@CMoH I don't understand your statement about releasing apifocal-parent. Yes the version needs updating in paeon.

**Comment by hzbarcea** [comment]
@azbarcea please leave just the .idea fixes in this PR. The others don't add value (the exec-maven-plugin ver should be handled another way).

**Comment by CMoH** [comment]
@hzbarcea I meant the exec-maven-plugin is defined in apifocal-parent version 8-SNAPSHOT, which can be released if needed. Otherwise ignore that comment

**Comment by hzbarcea** [comment]
Fixes already incorporated in the other PRs. Closing without merging.

**Pull request closed without merging**
